export const residents = {
  "A1": "Öztürk Açıkgöz",
  "A2": "Mehmet Gölcür",
  "A3": "Enes Kaşak",
  "A4": "Hüseyin Kabakoz",
  "A5": "Feryal Şahin",
  "A6": "Emre Serdar Atalay",
  "A7": "Mustafa Altınok",
  "A8": "Sezer Aydın",
  "A9": "Musa Karaçam",
  "A10": "Umut İpekoğlu",
  "A11": "Mehmet Çetin Ünal (Hurşit Bozkurt)",
  "A12": "Aydın Karaoğlu",
  "A13": "Feti Kılıçarslan",
  "A14": "Yavuz Beyazıtoğlu",
  "A15": "Dursun Çelik",
  "A16": "Sema Soyulmaz - Suat Kaya",
  "A17": "Mehtap Dinç",
  "A18": "Damra Eren Yalıcı",
  "A19": "Ali Erdoğan",
  "A20": "Furkan Hayrullah Baysal",
  "A21": "Yavuz Beyazıtoğlu",
  "A22": "Halil Tek",
  "A23": "Mustafa Kunter Yılmaz",
  "A24": "Kaan Burak Sorgunlu",
  "A25": "Selami Arslan",
  "A26": "Kerim Gülnar - Emel Gülnar",
  "A27": "Cihan Güneş - Hatice Erol Güneş",
  "A28": "Simay İşler",
  "A29": "Ali Pürlü / Dursun Pürlü / Emine Pürlü / Fevziye Bozkurt / Filiz Boyacıoğlu / Hüseyin Pürlü",
  "A30": "Ali Pürlü / Dursun Pürlü / Emine Pürlü / Fevziye Bozkurt / Filiz Boyacıoğlu / Hüseyin Pürlü",
  "A31": "Akas Enerji Ltd. Şti.",
  "A32": "Mustafa Macar",
  "A33": "Murat Altınok",
  "A34": "Sinan Akgöl",
  "A35": "Bora Erdoğan",
  "A36": "Gülser Yazıcıoğlu",
  "A37": "Murat Altınok",
  "A38": "Cemile Aksoy",
  "A39": "Nuran Acar - Beycan Acar",
  "A40": "Feryal Şahin",
  "A41": "Sinan Akgöl",
  "A42": "Mehmet Han Şeneren",
  "A43": "Mustafa Gökmen",
  "A44": "Tuğba Nazlı Büyüker Gül",
  "A45": "Emre Doğan",
  "A46": "Osman Nuri Çetin",
  "A47": "Mustafa Bulut / Nuray Bulut",
  "A48": "Murat Keleş",
  "A49": "Sevgi Talas",
  "A50": "Hülya Dinçelir - Neşet Dinçelir",
  "A51": "Hanefi Şahin",
  "A52": "Mecit Şahin",
  "A53": "Orhan Şahin",
  "A54": "Olgun Şahin",
  "A55": "Hasan Karakoç",
  "A56": "Ramazan Altın",
  "A57": "İmran Nezir",
  "A58": "Ümit Yalçın",
  "A59": "Gürhan Gürbüz",
  "A60": "Cengiz Yılmaz / Kemal Yılmaz / Mustafa Yılmaz / Müştak Bayar / Ömer Faruk Soylu / Süleyman Yılmaz / Zeki Yılmaz",
  "A61": "Cengiz Yılmaz / Kemal Yılmaz / Mustafa Yılmaz / Süleyman Yılmaz / Zeki Yılmaz",
  "A62": "Gamador İnşaat / Hurşit Bozkurt",
  "A63": "Atilla Deniz",
  "A64": "Cihat Günay",
  "A65": "Feryal Şahin",
  "A66": "Bekir Altınok",
  "A67": "Gökhan Fikri",
  "A68": "Türker Demir",
  "A69": "Bülent Karaçay",
  "A70": "Dursun Seyhan",
  "A71": "Davut Çalışkan",
  "A72": "Serdar Yılmaz",
  "A73": "Kadriye Ondağ - Mehmet Ondağ",
  "A74": "Bekir Altınok",
  "A75": "Selim Bingöl",
  "A76": "Büşra Markal",
  "A77": "Dursun Seyhan",
  "A78": "Dursun Seyhan",
  "A79": "Alişan Uslu",
  "A80": "Fikri Yücesan",
  "A81": "Ergül Ünsal",
  "A82": "Resul Ekrem Kılıç",
  "A83": "Adem Eren",
  "A84": "Murat Tel - Ali Tel",
  "A85": "Murat Tel - Ali Tel",
  "A86": "Duran Tosun",
  "B1": "Merve Yıldız",
  "B2": "Soner Öztürk",
  "B3": "Atilla İşler",
  "B4": "Abdullah Işık",
  "B5": "Burak Hacıoğlu",
  "B6": "Ahmet Kokurcan",
  "B7": "Emine Yalçın",
  "B8": "Muhsin Aktaş",
  "B9": "Cihan Adem Çınar",
  "B10": "Emine Toptaş",
  "B11": "Bayram Altuntaş",
  "B12": "Mustafa Ünalar",
  "B13": "Mustafa Ünalar",
  "B14": "Ali Galip Temel",
  "B15": "Hatice Asaloğlu",
  "B16": "Hacer Uludoğan",
  "B17": "Musa Karaçam",
  "B18": "Sevda Güler",
  "B19": "Mustafa Ünalar",
  "B20": "Mustafa Ünalar",
  "B21": "Mustafa Ünalar",
  "B22": "Hasan Özmen",
  "B23": "Mehmet Gürsoy",
  "B24": "Abdulkadir Demir",
  "B25": "Ulubey Değirmenci",
  "B26": "Abdul Qadeer Sayeed",
  "B27": "Zehra Tarı",
  "B28": "Ahmet Ragıp Değirmenci",
  "B29": "Yasemin Bülbül",
  "B30": "Halise Buculuğan",
  "B31": "Ahmet Nuri Taşçı",
  "B32": "Okursoy A.Ş. - İzzet Okursoy",
  "B33": "Osman Bağı",
  "B34": "Mehmet Aksu",
  "B35": "Şenay Ayaz-Hüsnü",
  "B36": "Mediha Oymak Er",
  "B37": "Nuran Acar - Beycan Acar",
  "B38": "Ömer Can Önder",
  "B39": "Nevzat Bor",
  "B40": "Ahmet Bican",
  "B41": "Adem Yıldırım",
  "B42": "Nevzat Bor",
  "B43": "Mustafa Ünalar",
  "B44": "Mustafa Ünalar",
  "B45": "Mustafa Ünalar",
  "B46": "Özkan Korkmaz",
  "B47": "Nevzat Bor",
  "B48": "Nevzat Bor",
  "B49": "Nevzat Bor",
  "B50": "İlker Demirbaş",
  "B51": "Mustafa Ünalar",
  "B52": "Ayşegül Demir Yıldırım",
  "B53": "Ömer Faruk Büyüksoy - Recep Büyüksoy",
  "B54": "Emine Toptaş",
  "B55": "Mahmut Hüdai Karacabey",
  "B56": "Mustafa Ünalar",
  "B57": "Serhat Şimşek",
  "B58": "Sıddıka Konya",
  "B59": "Mustafa Ünalar",
  "B60": "Mustafa Ünalar",
  "B61": "Emre Şengül",
  "B62": "Mustafa Kemal Küçüksönmez",
  "B63": "Sevda Çelik Öztürk",
  "B64": "Özkan Öndeş",
  "B65": "Mehmet Fatih Kanoğlu",
  "B66": "Gürkan Güngör",
  "B67": "Azize Pala",
  "B68": "Mustafa Ünalar",
  "B69": "Mustafa Ünalar",
  "B70": "Nuran Acar - Beycan Acar",
  "B71": "Mustafa Ünalar",
  "B72": "Merve Er",
  "B73": "Semra Turan",
  "B74": "Mustafa Ünalar",
  "B75": "Mehmet Bıyık",
  "B76": "Ahmet Tufan",
  "B77": "Ercan Aktaş",
  "B78": "Hava Çakır Kızıltoprak",
  "B79": "Burak Koç",
  "B80": "Melih Ak",
  "B81": "Oktay Güzel",
  "B82": "Adil Han",
  "B83": "Ünsal Mutlu",
  "B84": "Abdul Qadeer Sayeed",
  "B85": "İbrahim Sinan Köçü",
  "B86": "Alican Ünal",
  "B87": "Nevzat Yıkman",
  "B88": "Mine Ekiz",
  "B89": "Caner Çelik",
  "B90": "Neris Bilgen Kureş",
  "B91": "Abdullah Aktaş",
  "B92": "Arif Demirdaş",
  "B93": "Dursun Altuntaş",
  "B94": "Yasin Avcı"
};